### ISSUE TITLE
By.what locator does not work on Firefox

### ISSUE THREAD

**Issue by demetriusnunes** [UseFedora/protractor-extras#1]
Stack:
    NoSuchElementError: No element found using locator: by.what("suggested mission")
      at Array.forEach (native)
      at runMicrotasksCallback (node.js:337:7)
      at process._tickCallback (node.js:355:11)

**Comment by demetriusnunes** [comment]
Ok, I was able to fix it. Just replacing the $().find for .querySelectorAll did the trick - I suspect the object returned by jQuery was not an 'array-like' object in the eyes of Firefox.

So, lines 29 and 30 became this:
```
    elements = (parent or document).querySelectorAll("[what=\"" + what + "\"]")
    return [elements[0]] if firstOnly
```

**Comment by cjroth** [comment]
Closed, fixed via https://github.com/UseFedora/protractor-extras/commit/1db697a1df62f31aac582ec9da96c20dfef84bf8

**Comment by cjroth** [comment]
Thanks!
